server:
  port: ${APP_PORT}
  error:
    include-message: always
    include-binding-errors: always

oauth:
  google:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    scope: "openid profile email"

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  application:
    name: gateway

  config:
    import: optional:consul:/

  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        health-check-path: /health

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

frontend:
  url: ${FRONTEND_URL}